export const SET_SKILL_GEM_DATA = 'SET_SKILL_GEM_DATA';
export const SET_CURRENCY_DATA = 'SET_CURRENCY_DATA';
export const SET_CURRENCY_DETAIL_DATA = 'SET_CURRENCY_DETAIL_DATA';
export const SET_SKILL_QUALITY_DATA = 'SET_SKILL_QUALITY_DATA';
